####################################################################################################
# Ollama configuration parameters
####################################################################################################
protocol:
  name: "ollama"
  api_url: http://localhost:11434
  model:
    name: "llama3.1:latest"
####################################################################################################
# WatsonX configuration parameters
####################################################################################################
# protocol:
#   name: "watsonx"
#   api_url: "https://eu-de.ml.cloud.ibm.com"
#   space_id: "dd2dd8ef-a711-4919-a61b-b6115becd96a"
#   model:
#     name: "ibm/granite-4-h-small"
#     parameters:
#       decoding_method: sample
#       min_new_tokens: 1
#       max_new_tokens: 500
####################################################################################################
# OpenAI configuration parameters
####################################################################################################
# protocol:
#   name: "openai"
#   # You can use:
#   # - https://api.openai.com/v1 for ChatGPT
#   api_url: "http://localhost:11434/v1"
#   model:
#     # You can use:
#     # - "gpt-3.5-turbo" for ChatGPT 3.5
#     # - "gpt-4" for ChatGPT 4
#     # - "instructlab/merlinite-7b-lab" for InstructLab and Merlinite model
#     name: "llama3.1:latest"

####################################################################################################
# System Message Prompt
####################################################################################################
system_message: |
  You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.
  Please ensure that your responses are socially unbiased and positive in nature.
  If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct.
  If you don't know the answer to a question, please don't share false information.

####################################################################################################
# Chatterpy Logging
####################################################################################################
log:
  level: "DEBUG"
  console: false
  file: "logs/chat.log"
  rotation: "10 MB"
  retention: "7 days"
  compression: "zip"
